    access_tier                    = "Hot"
    account_kind                   = "StorageV2"
    account_replication_type       = "LRS"
    account_tier                   = "Standard"
    name                           = "satempdemo"
    resource_group_name            = "rg-demo"
    location                       = "eastus"
    min_tls_version                = "TLS1_2"
    tags ={}